version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database_name
    ports:
      - "5432:5432"

  web:
    image: flutproj-web:latest
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "db"
      DB_USER: "my_user"
      DB_PASSWORD: "my_password"
      DB_NAME: "my_database_name"
    depends_on:
      - db

  frontend:
    image: flutproj-frontend-static:latest
    ports:
      - "8080:80"
    depends_on:
      - web
